services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: norms
      POSTGRES_USER: norms
      POSTGRES_PASSWORD: norms
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  pgweb:
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: postgres://norms:norms@postgres:5432/norms?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  pg_data:
  redis_data:
