# Версия Node.js
FROM node:22.15.0

# Рабочая директория внутри контейнера Backend-части продукта Docker Compose
WORKDIR /nest-backend

# Копируем package.json и package-lock.json для установки зависимостей
COPY ./package.json          ./package.json
COPY ./package-lock.json     ./package-lock.json

# Устанавливаем NPM зависимости для работы Backend-части продукта
RUN npm install --verbose

# Копируем все остальные файлы проекта
COPY ./ ./

# Объявляем порт 3000 доступным для открытия внутри контейнера Backend-части продукта Docker Compose
EXPOSE 3000

# Запускаем Backend-часть продукта внутри контейнера Docker Compose в режиме разработки и слежки за изменением файлов с кодом
CMD ["sh", "-c", "npm run start:debug --verbose"]
