services:
  # Сервис СуБД MySQL
  mysql_norms_dev: # Наименование сервиса Docker
    container_name: mysql_norms_dev # Наименование контейнера Docker
    image: mysql:8.4 # Актуальная LTS-версия MySQL
    restart: unless-stopped # Если оборудование где запущены докер контейнеры упало, то Docker после запуска системы посмотрит и поднимет только в случае если контейнер работал до падения
    env_file: # Прокидываем переменные среды из корня nest-backend
      - ./../../.env
    environment: # Переменные среды внутри контейнера mysql_norms_dev
      - MYSQL_DATABASE=mysql_norms_dev # Прокидываем наименование базы данных в СуБД MySQL
      - MYSQL_USER=${MYSQL_USER} # Прокидываем логин пользователя в переменные среды контейнера Docker для того чтобы пользователь смог использовать СуБД MySQL
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} # Прокидываем пароль пользователя в переменные среды контейнера Docker для того чтобы пользователь смог использовать СуБД MySQL
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Прокидываем ROOT пароль в переменные среды контейнера Docker для корректной работы СуБД MySQL из .env файла
    volumes: # Тома для обмена данными хостовой машины и операционной системой внутри Docker контейнера
      - ./../sql-files/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./../sql-files/init.sql:/docker-entrypoint-initdb.d/init.sql:ro # При первичной инициализации возьмет файл init.sql и на основе него создаст таблицы в базе данных СуБД MySQL
      - ./../volumes/db_data:/var/lib/mysql # Сохранит прогресс работы СуБД MySQL вне контейнера Docker
    expose: # Объявление для Docker о необходимых портах внутри контейнера Docker
      - ${MYSQL_PORT}
    ports: # Прокидывание портов наружу из контейнера Docker
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks: # Сети в которых этот контейнер Docker смогут находить другие контейнеры Docker
      - network_norms_project
  # Сервис СуБД MySQL

  # Сервис phpMyAdmin
  pma_norms_dev: # Наименование сервиса Docker
    container_name: pma_norms_dev # Наименование контейнера Docker
    image: phpmyadmin:5.2 # Зафиксированная версия phpMyAdmin
    restart: unless-stopped # Если оборудование где запущены докер контейнеры упало, то Docker после запуска системы посмотрит и поднимет только в случае если контейнер работал до падения
    env_file: # Прокидываем переменные среды из корня nest-backend
      - ./../../.env
    environment: # Переменные среды внутри контейнера pma_norms_dev
      - PMA_ARBITRARY=0 # При значении 1 разрешено подключаться к произвольному серверу
      - PMA_HOST=mysql_norms_dev # Здесь указываем через "=" наименование контейнера-сервиса Docker для СуБД MySQL
      - PMA_PORT=${MYSQL_PORT} # Здесь указываем переменную порта работы СуБД MySQL контейнера Docker из .env
    expose: # Объявление для Docker о необходимых портах внутри контейнера Docker
      - ${PMA_INTERNAL_PORT}
    ports: # Прокидывание портов наружу из контейнера Docker
      - ${PMA_EXTERNAL_PORT}:${PMA_INTERNAL_PORT}
    networks: # Сети в которых этот контейнер Docker смогут находить другие контейнеры Docker
      - network_norms_project
    depends_on: # Заставляем контейнер phpMyAdmin ждать перечисленные контейнеры
      - mysql_norms_dev
  # Сервис phpMyAdmin

  # Сервис Backend-части проекта
  nestbackend_norms_dev: # Наименование сервиса Docker
    container_name: nestbackend_norms_dev # Наименование контейнера Docker
    build: # Правила сборки сервиса Docker
      context: ./../../ # Контекст сборки — корень nest-backend (на два уровня выше docker/compose-files)
      dockerfile: ./docker/dockerfiles/nest-backend/Dockerfile.dev # Путь до Dockerfile (наш самописный image)
    restart: unless-stopped # Если оборудование где запущены докер контейнеры упало, то Docker после запуска системы посмотрит и поднимет только в случае если контейнер работал до падения
    env_file: # Прокидываем переменные среды из корня nest-backend
      - ./../../.env
    environment: # Переменные среды внутри контейнера nestbackend_norms_dev
      - CHOKIDAR_USEPOLLING=true
      - MYSQL_HOST_AND_NAME_DATABASE=mysql_norms_dev
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ACCESS_KEY_JWT=${ACCESS_KEY_JWT}
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME}
      - REFRESH_KEY_JWT=${REFRESH_KEY_JWT}
      - REFRESH_TOKEN_LIFETIME=${REFRESH_TOKEN_LIFETIME}
      - BACKEND_PORT_RESTAPI=${BACKEND_PORT_RESTAPI}
      - BACKEND_PORT_WEBSOCKET=${BACKEND_PORT_WEBSOCKET}
    volumes: # Тома для обмена данными хостовой машины и операционной системой внутри Docker контейнера
      - ./../../src:/nest-backend/src:rw
      # TODO: ElmirKuba 2026-04-16: Расскоментировать строку ниже когда потребуется создаваемые backend частью проекта файлы сохранять между перезапусками контейнеров отдавая их на хостовую машину
      # - ./../../uploads:/nest-backend/uploads:rw
    command: sh -c "sleep 30s && npm run start:debug --verbose" # Команда которая поднимет через 30 секунд само приложение nest-backend внутри docker контейнера
    expose: # Объявление для Docker о необходимых портах внутри контейнера Docker
      - ${BACKEND_PORT_RESTAPI}
      - ${BACKEND_PORT_WEBSOCKET}
    ports: # Прокидывание портов наружу из контейнера Docker
      - ${BACKEND_PORT_RESTAPI}:${BACKEND_PORT_RESTAPI}
      - ${BACKEND_PORT_WEBSOCKET}:${BACKEND_PORT_WEBSOCKET}
    networks: # Сети в которых этот контейнер Docker смогут находить другие контейнеры Docker
      - network_norms_project
    depends_on: # Заставляем контейнер backend ждать перечисленные контейнеры
      - pma_norms_dev
      - mysql_norms_dev
  # Сервис Backend-части проекта

# Сети Docker Compose
networks:
  # Сеть Docker Compose продукта для разработки
  network_norms_project:
    name: network_norms_project
    external: true # Сеть с таким именем создаётся вручную (явный контроль)
    # network network_norms_project declared as external, but could not be found
    # Исп.: docker network create network_norms_project
